# Generated by Django 4.1 on 2022-08-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='age_limit_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
